apiVersion: v1
kind: ServiceAccount
metadata:
  name: stripe-provider
  namespace: stripe-provider-system
  labels:
    app.kubernetes.io/name: stripe-provider
    app.kubernetes.io/managed-by: kustomize
