---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stripe-provider
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - billingaccounts
  - paymentmethodclasses
  - paymentmethods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - billing.miloapis.com
  resources:
  - paymentmethods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stripe.billing.miloapis.com
  resources:
  - stripepaymentmethods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stripe.billing.miloapis.com
  resources:
  - stripepaymentmethods/finalizers
  verbs:
  - update
- apiGroups:
  - stripe.billing.miloapis.com
  resources:
  - stripepaymentmethods/status
  - stripeproviderconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stripe.billing.miloapis.com
  resources:
  - stripeproviderconfigs
  verbs:
  - get
  - list
  - watch
