//go:build !ignore_autogenerated

/*
Copyright 2026 Datum Technology Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodLocalRef) DeepCopyInto(out *PaymentMethodLocalRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodLocalRef.
func (in *PaymentMethodLocalRef) DeepCopy() *PaymentMethodLocalRef {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodLocalRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripeCardInstrumentDetails) DeepCopyInto(out *StripeCardInstrumentDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripeCardInstrumentDetails.
func (in *StripeCardInstrumentDetails) DeepCopy() *StripeCardInstrumentDetails {
	if in == nil {
		return nil
	}
	out := new(StripeCardInstrumentDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripeInstrumentDetails) DeepCopyInto(out *StripeInstrumentDetails) {
	*out = *in
	if in.Card != nil {
		in, out := &in.Card, &out.Card
		*out = new(StripeCardInstrumentDetails)
		**out = **in
	}
	if in.USBankAccount != nil {
		in, out := &in.USBankAccount, &out.USBankAccount
		*out = new(StripeUSBankAccountInstrumentDetails)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripeInstrumentDetails.
func (in *StripeInstrumentDetails) DeepCopy() *StripeInstrumentDetails {
	if in == nil {
		return nil
	}
	out := new(StripeInstrumentDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripePaymentMethod) DeepCopyInto(out *StripePaymentMethod) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripePaymentMethod.
func (in *StripePaymentMethod) DeepCopy() *StripePaymentMethod {
	if in == nil {
		return nil
	}
	out := new(StripePaymentMethod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StripePaymentMethod) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripePaymentMethodList) DeepCopyInto(out *StripePaymentMethodList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StripePaymentMethod, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripePaymentMethodList.
func (in *StripePaymentMethodList) DeepCopy() *StripePaymentMethodList {
	if in == nil {
		return nil
	}
	out := new(StripePaymentMethodList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StripePaymentMethodList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripePaymentMethodSpec) DeepCopyInto(out *StripePaymentMethodSpec) {
	*out = *in
	out.PaymentMethodRef = in.PaymentMethodRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripePaymentMethodSpec.
func (in *StripePaymentMethodSpec) DeepCopy() *StripePaymentMethodSpec {
	if in == nil {
		return nil
	}
	out := new(StripePaymentMethodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripePaymentMethodStatus) DeepCopyInto(out *StripePaymentMethodStatus) {
	*out = *in
	if in.SetupIntent != nil {
		in, out := &in.SetupIntent, &out.SetupIntent
		*out = new(StripeSetupIntentStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfirmedAt != nil {
		in, out := &in.ConfirmedAt, &out.ConfirmedAt
		*out = (*in).DeepCopy()
	}
	if in.Instrument != nil {
		in, out := &in.Instrument, &out.Instrument
		*out = new(StripeInstrumentDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripePaymentMethodStatus.
func (in *StripePaymentMethodStatus) DeepCopy() *StripePaymentMethodStatus {
	if in == nil {
		return nil
	}
	out := new(StripePaymentMethodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripeProviderConfig) DeepCopyInto(out *StripeProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripeProviderConfig.
func (in *StripeProviderConfig) DeepCopy() *StripeProviderConfig {
	if in == nil {
		return nil
	}
	out := new(StripeProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StripeProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripeProviderConfigList) DeepCopyInto(out *StripeProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StripeProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripeProviderConfigList.
func (in *StripeProviderConfigList) DeepCopy() *StripeProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(StripeProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StripeProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripeProviderConfigSpec) DeepCopyInto(out *StripeProviderConfigSpec) {
	*out = *in
	in.SecretKeyRef.DeepCopyInto(&out.SecretKeyRef)
	in.WebhookSecretRef.DeepCopyInto(&out.WebhookSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripeProviderConfigSpec.
func (in *StripeProviderConfigSpec) DeepCopy() *StripeProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(StripeProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripeProviderConfigStatus) DeepCopyInto(out *StripeProviderConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SupportedTaxIDTypes != nil {
		in, out := &in.SupportedTaxIDTypes, &out.SupportedTaxIDTypes
		*out = make([]SupportedTaxIDType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripeProviderConfigStatus.
func (in *StripeProviderConfigStatus) DeepCopy() *StripeProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(StripeProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripeSetupIntentStatus) DeepCopyInto(out *StripeSetupIntentStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripeSetupIntentStatus.
func (in *StripeSetupIntentStatus) DeepCopy() *StripeSetupIntentStatus {
	if in == nil {
		return nil
	}
	out := new(StripeSetupIntentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripeUSBankAccountInstrumentDetails) DeepCopyInto(out *StripeUSBankAccountInstrumentDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripeUSBankAccountInstrumentDetails.
func (in *StripeUSBankAccountInstrumentDetails) DeepCopy() *StripeUSBankAccountInstrumentDetails {
	if in == nil {
		return nil
	}
	out := new(StripeUSBankAccountInstrumentDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupportedTaxIDType) DeepCopyInto(out *SupportedTaxIDType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupportedTaxIDType.
func (in *SupportedTaxIDType) DeepCopy() *SupportedTaxIDType {
	if in == nil {
		return nil
	}
	out := new(SupportedTaxIDType)
	in.DeepCopyInto(out)
	return out
}
