apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stripe-provider
  labels:
    app.kubernetes.io/name: stripe-provider
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: stripe-provider
      control-plane: stripe-provider
  endpoints:
    - port: metrics
      interval: 30s
      honorLabels: true
