name: Publish Docker Image

on:
  push:
  release:
    types: ['published']

jobs:
  publish-container-image:
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: datum-cloud/actions/.github/workflows/publish-docker.yaml@v1.14.0
    with:
      image-name: stripe-provider
      registry-organization: milo-os
      platforms: linux/amd64,linux/arm64
    secrets: inherit

  publish-kustomize-bundles:
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: datum-cloud/actions/.github/workflows/publish-kustomize-bundle.yaml@v1.14.0
    with:
      bundle-name: ghcr.io/milo-os/stripe-provider-kustomize
      bundle-path: config
      image-overlays: config/base/manager
      image-name: ghcr.io/milo-os/stripe-provider
    secrets: inherit
